### PR TITLE
Add Kubernetes Service to Recommendation service

### PR DESCRIPTION
**Pull request by adrsamanta**

### CODE REVIEW

**Comment by DavidSouther** [comment]
Could you write a quick summary of why this is necessary?

**Comment by adrsamanta** [comment]
In order for istio to route traffic correctly, it needs a kubernetes service to route traffic to the workloads in question. I don't have a thorough understand of how this works, but based on the comment here: https://github.com/istio/istio/issues/9504#issuecomment-436864468 it seems this is our issue.

**Comment by DavidSouther** [comment]
As a comment in the file, please :)

**Comment by adrsamanta** [comment]
Done

**Review by DavidSouther — APPROVED** [review]

**Pull request merged**
